### ISSUE TITLE
Error in DatePeriodUtil

### ISSUE THREAD

**Issue by evoelise** [kirelandnatwest/car-rental-task#3]
There's an error in the `DatePeriodUtil` code. See internal email I will send with more details.

This is easily illustrated with the following unit test that can be added to `DatePeriodUtilTest` code:

```
    private static final DatePeriod WHOLLY_COVERS_PERIOD = new DatePeriod(BASE_PERIOD.getStart().minus(Period.ofDays(1)), 
    		BASE_PERIOD.getEnd().plus(Period.ofDays(1)));

    @Test
    void testForOverlappingPeriodsWithWholePeriodOverlap() {
        assertThat(DatePeriodUtil.areOverlapping(BASE_PERIOD, WHOLLY_COVERS_PERIOD)).isTrue();
    }

```

You will see the last clause in the `DatePeriodUtil` code is incorrect.

**Comment by evoelise** [comment]
Note the same error exists in the Python version - I will raise a pull request for that too.

**Comment by nicwit** [comment]
Change merged
